import { Pet, Shelter, User } from '../../types/models.js';

export const mockData: {
  pets: Pet[];
  shelters: Shelter[];
  users: User[];
} = {
  pets: [
    {
      id: '1',
      name: 'Buddy',
      species: 'dog',
      breed: 'Golden Retriever',
      age: 3,
      size: 'large',
      description: 'Friendly and energetic dog',
      status: 'available',
      shelterId: '1',
    },
    {
      id: '2',
      name: 'Whiskers',
      species: 'cat',
      breed: 'Siamese',
      age: 2,
      size: 'small',
      description: 'Quiet and independent cat',
      status: 'available',
      shelterId: '2',
    },
    {
      id: '3',
      name: 'Luna',
      species: 'cat',
      breed: 'Maine Coon',
      age: 4,
      size: 'large',
      description: 'Majestic and gentle giant, loves cuddles',
      status: 'available',
      shelterId: '1',
    },
    {
      id: '4',
      name: 'Max',
      species: 'dog',
      breed: 'German Shepherd',
      age: 2,
      size: 'large',
      description: 'Smart and protective, good with training',
      status: 'pending',
      shelterId: '3',
    },
    {
      id: '5',
      name: 'Charlie',
      species: 'dog',
      breed: 'Beagle',
      age: 1,
      size: 'medium',
      description: 'Playful puppy, great with kids',
      status: 'available',
      shelterId: '2',
    },
    {
      id: '6',
      name: 'Oliver',
      species: 'cat',
      breed: 'British Shorthair',
      age: 5,
      size: 'medium',
      description: 'Calm and dignified, perfect lap cat',
      status: 'available',
      shelterId: '4',
    },
    {
      id: '7',
      name: 'Rocky',
      species: 'dog',
      breed: 'Rottweiler',
      age: 3,
      size: 'large',
      description: 'Gentle giant, well trained',
      status: 'adopted',
      shelterId: '1',
    },
  ],

  shelters: [
    {
      id: '1',
      name: 'Happy Paws Shelter',
      address: '123 Pet Street',
      city: 'Petville',
      state: 'CA',
      phone: '555-0001',
      email: 'contact@happypaws.com',
    },
    {
      id: '2',
      name: 'Furry Friends Rescue',
      address: '456 Animal Avenue',
      city: 'Pawtown',
      state: 'CA',
      phone: '555-0002',
      email: 'info@furryfriendsrescue.com',
    },
    {
      id: '3',
      name: 'Paws & Claws Haven',
      address: '789 Rescue Road',
      city: 'San Francisco',
      state: 'CA',
      phone: '555-0003',
      email: 'help@pawsandclaws.org',
    },
    {
      id: '4',
      name: 'Second Chance Sanctuary',
      address: '321 Hope Lane',
      city: 'Oakland',
      state: 'CA',
      phone: '555-0004',
      email: 'info@secondchance.org',
    },
    {
      id: '5',
      name: 'Guardian Angels Pet Rescue',
      address: '555 Shelter Drive',
      city: 'Berkeley',
      state: 'CA',
      phone: '555-0005',
      email: 'contact@guardianangels.com',
    },
  ],

  users: [
    {
      id: '1',
      name: 'John Doe',
      email: 'john@example.com',
      phone: '555-0123',
      preferences: {
        species: ['dog', 'cat'],
        size: ['medium', 'large'],
      },
    },
    {
      id: '2',
      name: 'Jane Smith',
      email: 'jane@example.com',
      phone: '555-0124',
      preferences: {
        species: ['cat'],
        size: ['small'],
      },
    },
    {
      id: '3',
      name: 'Mike Johnson',
      email: 'mike@example.com',
      phone: '555-0125',
      preferences: {
        species: ['dog'],
        size: ['large'],
      },
    },
    {
      id: '4',
      name: 'Sarah Wilson',
      email: 'sarah@example.com',
      phone: '555-0126',
      preferences: {
        species: ['dog', 'cat'],
        size: ['small', 'medium'],
      },
    },
    {
      id: '5',
      name: 'David Brown',
      email: 'david@example.com',
      phone: '555-0127',
      preferences: {
        species: ['cat'],
        size: ['medium', 'large'],
      },
    },
  ],
};
